Scalar -> Single number

Vector -> Ordered list of numbers. It represents single data point with multiple attributes

In [1]:
import numpy as np


# area, num_of_bedrooms, num_of_balconies
house_vector = np.array([2400, 3, 2])
print(f'House Vector: {house_vector}')
print(f'Shape of the vector: {house_vector.shape}')

House Vector: [2400    3    2]
Shape of the vector: (3,)


Matrix

1. Transpose Operation

A matrix representing the ratings of 3 users for 4 movies.

In [2]:
ratings_matrix = np.array([
    [5, 4, 1, 2], # user 1 ratings
    [1, 2, 5, 4], # user 2 ratings
    [4, 3, 2, 5]  # user 3 ratings
])

print(ratings_matrix)

[[5 4 1 2]
 [1 2 5 4]
 [4 3 2 5]]


In [3]:
transposed_matrix = ratings_matrix.T
print(transposed_matrix)

[[5 1 4]
 [4 2 3]
 [1 5 2]
 [2 4 5]]


2. Matrix Multiplication

In [4]:
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
B = np.array([[1, 5, 7], [2, 4, 6], [7, 9, 11]])

print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [5]:
print(B)

[[ 1  5  7]
 [ 2  4  6]
 [ 7  9 11]]


In [6]:
# perform element-wise matrix multiplication
y = A * B
print(y)

[[ 1 10 21]
 [ 8 20 36]
 [49 72 99]]


In [7]:
# perform matrix multiplication
y = A @ B
print(y)

[[ 26  40  52]
 [ 56  94 124]
 [ 86 148 196]]


Special Matrix

1. Identity Matrix

In [8]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


2. Diagonal Matrix

In [10]:
np.diag([100, 1000, 2000])

array([[ 100,    0,    0],
       [   0, 1000,    0],
       [   0,    0, 2000]])

Linear Transformations

In [12]:
v_likes = np.array([10, 2, 5])
v_comments = np.array([4, 1, 3])

# create a new feature vector via linear combination
v_engagement = 0.4 * v_likes + 0.6 * v_comments
print(f'Engagement score vector: {v_engagement}')

Engagement score vector: [6.4 1.4 3.8]


Inner Product Geometry

Dot Product (u, v)

In [13]:
w = np.array([0.7, -0.2, 0.1])
x = np.array([10, 20, 5]) #[temp, humidity, wind_speed]

score = np.dot(w, x)
print(score)

3.5


Norm (Length, ||v||)

In [14]:
w = np.array([0.7, -0.2, 0.1])

np.linalg.norm(w)

np.float64(0.7348469228349533)

In [15]:
## two user's rating vectors
active_user = np.array([5, 4, 5, 5])
passive_user = np.array([1, 0, 2, 0])


active_norm = np.linalg.norm(active_user)
passive_norm = np.linalg.norm(passive_user)

print(active_norm)

9.539392014169456


In [16]:
print(passive_norm)

2.23606797749979


Cosine Similarity

In [17]:
doc1 = np.array([30, 25, 20, 0, 1])
doc2 = np.array([5, 4, 3, 0, 0])
doc3 = np.array([0, 1, 0, 40, 30])

# calculate the cosine similarity of doc1 and doc2
dot_product_12 = np.dot(doc1, doc2)
norm_doc1 = np.linalg.norm(doc1)
norm_doc2 = np.linalg.norm(doc2)
similarity_12 = dot_product_12 / (norm_doc1 * norm_doc2)

# calculate the cosine similarity of doc2 and doc3
dot_product_23 = np.dot(doc2, doc3)
norm_doc2 = np.linalg.norm(doc2)
norm_doc3 = np.linalg.norm(doc3)
similarity_23 = dot_product_23 / (norm_doc2 * norm_doc3)


# calculate the cosine similarity of doc2 and doc3
dot_product_13 = np.dot(doc1, doc3)
norm_doc1 = np.linalg.norm(doc1)
norm_doc3 = np.linalg.norm(doc3)
similarity_13 = dot_product_13 / (norm_doc1 * norm_doc3)

print(f'Similarity(Doc1, Doc2): {similarity_12}')
print(f'Similarity(Doc2, Doc3): {similarity_23}')
print(f'Similarity(Doc1, Doc3): {similarity_13}')

Similarity(Doc1, Doc2): 0.9989610386805191
Similarity(Doc2, Doc3): 0.011311446435881278
Similarity(Doc1, Doc3): 0.025059805864160723


In [18]:
mat = np.array([[2.5, -0.5],
                [-0.5, 2.5]])

eigen_values, eigen_vectors = np.linalg.eig(mat)

print(f'Eigen Values are: {eigen_values}')
print(f'Eigen Vectors are: {eigen_vectors}')

Eigen Values are: [3. 2.]
Eigen Vectors are: [[ 0.70710678  0.70710678]
 [-0.70710678  0.70710678]]


In [19]:
pc1 = eigen_vectors[:, 0]
pc2 = eigen_vectors[:, 1]

pc1

array([ 0.70710678, -0.70710678])

In [20]:
pc2

array([0.70710678, 0.70710678])