In [50]:

#load the wine dataset and perform classification using Random Forest Classifier
from sklearn.datasets import load_wine
#load model selection tools for splitting the dataset into training and testing sets
from sklearn.model_selection import train_test_split
#load the Random Forest Classifier model
from sklearn.ensemble import RandomForestClassifier
#load metrics for evaluating the performance of the model
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
import numpy as np
import pandas as pd

# Load the wine dataset
wine = load_wine()

# print(wine.feature_names)

#create a DataFrame from the wine dataset
data = pd.DataFrame(wine.data, columns=wine.feature_names)
# print(wine.target_names)
# data['target'] = wine.target
# print(data.head())
# X = data.drop('target', axis=1)

X = data

y = wine.target_names[wine.target] #wine.target is an array of integers representing the class labels, and

x_train,x_test,y_train,y_test = train_test_split(X,y, test_size=0.2, random_state=42)
# print(x_train.head())

model = RandomForestClassifier()

model.fit(x_train, y_train)

y_pred = model.predict(x_test)
print(y_pred)

print("Actual labels:")
print(y_test)




['class_0' 'class_0' 'class_2' 'class_0' 'class_1' 'class_0' 'class_1'
 'class_2' 'class_1' 'class_2' 'class_0' 'class_2' 'class_0' 'class_1'
 'class_0' 'class_1' 'class_1' 'class_1' 'class_0' 'class_1' 'class_0'
 'class_1' 'class_1' 'class_2' 'class_2' 'class_2' 'class_1' 'class_1'
 'class_1' 'class_0' 'class_0' 'class_1' 'class_2' 'class_0' 'class_0'
 'class_0']
Actual labels:
['class_0' 'class_0' 'class_2' 'class_0' 'class_1' 'class_0' 'class_1'
 'class_2' 'class_1' 'class_2' 'class_0' 'class_2' 'class_0' 'class_1'
 'class_0' 'class_1' 'class_1' 'class_1' 'class_0' 'class_1' 'class_0'
 'class_1' 'class_1' 'class_2' 'class_2' 'class_2' 'class_1' 'class_1'
 'class_1' 'class_0' 'class_0' 'class_1' 'class_2' 'class_0' 'class_0'
 'class_0']


In [47]:
#check the accuracy of the model
accuracy_score = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy_score:.2f}")

Accuracy: 1.00


In [48]:
classification_rep = classification_report(y_test, y_pred)
print("Classification Report:")
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

     class_0       1.00      1.00      1.00        14
     class_1       1.00      1.00      1.00        14
     class_2       1.00      1.00      1.00         8

    accuracy                           1.00        36
   macro avg       1.00      1.00      1.00        36
weighted avg       1.00      1.00      1.00        36



In [44]:
confusion_matrix = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:")
print(confusion_matrix)

Confusion Matrix:
[[14  0  0]
 [ 0 14  0]
 [ 0  0  8]]
