***Creating NumPy Arrays**

In [2]:
import numpy as np


In [3]:
#Creating a 1D NumPy array
arr1 = np.array([1,2,3,4,5])
print(arr1)

[1 2 3 4 5]


In [22]:
#Creating a 2D NumPy array
arr2 = np.array([[1,2,3,4],[5,6,7,8]])
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [23]:
#Creating a 3D NumPy array
arr3 = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(arr3)


[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [14]:
#All zero
zero_arr = np.zeros((3,5,5))
print(zero_arr)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [15]:
#All ones
zero_arr = np.ones((3,5,5))
print(zero_arr)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


In [31]:
#range
range_arr = np.arange(0,12,2)    # range
print(range_arr)

[ 0  2  4  6  8 10]


In [32]:
#full
full_arr = np.full((3,4),8)
print(full_arr)

[[8 8 8 8]
 [8 8 8 8]
 [8 8 8 8]]


In [33]:
#eye
i = np.eye(4) 
print(i)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [19]:
arrr = np.linspace(0,1,10)   # equal intervals
print(arrr)

[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


***Shape & Info***

In [24]:
print(arr3.shape)      # size

(1, 3, 3)


In [26]:
print(arr3.ndim)       # dimension

3


In [27]:
print(arr3.dtype)



int64


***Memory Efficiency***

In [30]:
import sys
list_data = list(range(1000))
numpy_data = np.array(list_data)
# print(numpy_data)
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


***Vectorization – No More Loops!***

NumPy avoids loops by applying operations to entire arrays at once using SIMD (Single Instruction, Multiple Data) and other low-level optimizations. SIMD is a CPU-level optimization provided by
modern processors.

In [35]:
# Python list (loop-based)
#list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
# numpy_squares = arr1 ** 2

***Changing Data Types***


In [37]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32



arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

float32
[1 2 3]


***Reshaping and Flattening Arrays***

In [41]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # (2, 3)

reshaped = arr.reshape((3, 2))  # Change shape
print(reshaped)

flattened = arr.flatten()  # Convert 2D → 1D
print(flattened)  # [1 2 3 4 5 6]

(2, 3)
[[1 2]
 [3 4]
 [5 6]]
[1 2 3 4 5 6]
