***Indexing***


In [2]:
import numpy as np

In [4]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(arr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [5]:
#convert into 1D array
flat = arr.flatten()
print(flat)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [6]:
#Indexing
print(flat[0])

1


In [7]:
print(flat[-1])

12


***Slicing***

In [12]:
arr = np.array([10, 20, 30, 40, 50])
 
print(arr[1:4])  # [20 30 40] (slice from index 1 to 3)
print(arr[:3])   # [10 20 30] (first 3 elements)
print(arr[::2])  # [10 30 50] (every 2nd element)

[20 30 40]
[10 20 30]
[10 30 50]


In [9]:
sliced = arr[1:4]
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[ 10 999  30  40  50]


In [13]:
sliced = arr[1:4].copy()
sliced[0] = 999
print(arr)  # [10 999 30 40 50]

[10 20 30 40 50]


***Fancy Indexing***

In [14]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


***Boolean Masking***

In [15]:
arr = np.array([10, 20, 30, 40, 50])
mask = arr > 25  # Condition: values greater than 25
print(arr[mask])  # [30 40 50]

[30 40 50]
