In [2]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],[1,2,3],[1,2,3]])

In [4]:
arr


array([[1, 2, 3],
       [1, 2, 3],
       [1, 2, 3]])

In [9]:
#Mathematical Functions
np.sum(arr,axis=1)

array([6, 6, 6])

In [11]:
# Indexing in Multidimensional Arrays
arr[0:2,0:3]

array([[1, 2, 3],
       [1, 2, 3]])

In [12]:
#Indexing in 3D Arrays
arr = np.array([
[[1,2,3],[4,5,6],[7,8,9]],
[[10,11,12],[13,15,16],[17,18,19]]      
])

In [15]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 15, 16],
        [17, 18, 19]]])

In [16]:
print(arr.shape)

(2, 3, 3)


In [24]:
#Accessing elements in 3D:
print(arr[0, 1, 2])  # Output: 6
 
print(arr[:, 0, :])   # Get the first row from both sheets
print(arr[1,1,1])

print(arr[1,1,1])

print(arr[1,0:2,1:3])

6
[[ 1  2  3]
 [10 11 12]]
15
15
[[11 12]
 [15 16]]


In [27]:
#Changing Data Along an Axis
arr[0,:, 1] = 0
print(arr)

[[[ 1  0  3]
  [ 0  0  0]
  [ 7  0  9]]

 [[10 11 12]
  [ 0  0  0]
  [17 18 19]]]
