In [2]:
import numpy as np
from scipy import stats

# observed values from the table
observed_values = np.array([[50, 30, 20],
                            [30, 40, 30],
                            [20, 30, 50]])

# perform chi-square test of independence
chi2_stat, p_val, dof, expected_values = stats.chi2_contingency(observed_values)

In [8]:
print(chi2_stat)

30.0


In [3]:
print(dof)

4


In [4]:
print(expected_values)

[[33.33333333 33.33333333 33.33333333]
 [33.33333333 33.33333333 33.33333333]
 [33.33333333 33.33333333 33.33333333]]


In [5]:
print(p_val)

4.894437128029217e-06


In [7]:
alpha = 0.05

if p_val < alpha:
  print('Reject the H0 -> There is a significant association between age group and product preferences.')
else:
  print('Fail to reject the H0 -> There is a no association between age group and product preferences.')

Reject the H0 -> There is a significant association between age group and product preferences.


ANOVA Test

In [9]:
group_A = [105,110,98,107,103]
group_B = [130,125,132,128,129]
group_C = [120,115,117,119,121]


# perform one-way ANOVA
f_stats, p_val = stats.f_oneway(group_A, group_B, group_C)

In [10]:
print(f_stats)

67.39634146341461


In [11]:
print(p_val)

2.984427460719471e-07


In [12]:
alpha = 0.05

if p_val < alpha:
  print('Reject the H0')
else:
  print('Fail to reject the H0')

Reject the H0


Confidence Interval

In [13]:
sample_mean = 0.98
sample_std = 0.1
sample_size = 40
alpha = 0.05
confidence_level = 0.95
z_score = 1.96


standard_error = sample_std / np.sqrt(sample_size)
confidence_interval = (sample_mean - z_score * standard_error, sample_mean + z_score * standard_error)
print(f'95% Confidence Interval: {confidence_interval}')

95% Confidence Interval: (np.float64(0.9490096789303498), np.float64(1.01099032106965))
