Array Creation

In [1]:
import numpy as np

arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
arr_3d = np.array([[[1, 2],
                    [3, 4]],

                   [[5, 6],
                    [7, 8]],

                   [[9, 10],
                    [11, 12]]])

In [2]:
print(arr_1d)

[1 2 3 4 5 6 7 8]


In [3]:
print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [4]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


Indexing

In [5]:
arr_1d[4]

np.int64(5)

In [6]:
arr_2d[2][1]

np.int64(8)

In [7]:
arr_2d[2, 1]

np.int64(8)

In [8]:
arr_3d[2][0][1]

np.int64(10)

In [9]:
arr_3d[2, 0, 1]

np.int64(10)

Slicing

In [10]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
print(arr_1d[2:4])

[3 4]


In [12]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12],
                   [13, 14, 15, 16]])

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [13]:
subarray = arr_2d[1:3, 1:3]
print(subarray)

[[ 6  7]
 [10 11]]


In [15]:
subarray = arr_2d[2:,2:]
print(subarray)

[[11 12]
 [15 16]]


In [16]:
print(arr_2d[:, 1:])

[[ 2  3  4]
 [ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [17]:
print(arr_2d[1:, 1:])

[[ 6  7  8]
 [10 11 12]
 [14 15 16]]


In [18]:
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])

print(arr_3d)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


In [27]:
subarray = arr_3d[:, 0, 0:2]

In [28]:
print(subarray)

[[ 1  2]
 [ 7  8]
 [13 14]]


Operations in arrays

Arithmetic Operations

1 Dimensional Array

In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# element wise addition
c = a + b
print(c)

[5 7 9]


In [30]:
d = a - b
print(d)

[-3 -3 -3]


In [31]:
e = a * b
print(e)

[ 4 10 18]


In [32]:
f = b / a
print(f)

[4.  2.5 2. ]


In [33]:
g = b // a
print(g)

[4 2 2]


In [34]:
h = a ** 2
print(h)

[1 4 9]


2 Dimensional Array

In [35]:
print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [36]:
print(arr_2d.transpose())

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


In [37]:
print(arr_2d.T)

[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


Sorting

In [39]:
arr1 = np.array([3, 1, 5, 2, 4, 9, 7, 8])
sorted_arr = np.sort(arr1)
print(sorted_arr)

[1 2 3 4 5 7 8 9]


In [40]:
arr2 = np.array([[5, 2, 3],
                 [8, 1, 6],
                 [7, 4, 9]])

# sort the data along axis = 0 meaning column wise
sorted_arr_axis0 = np.sort(arr2, axis=0)
print(sorted_arr_axis0)

[[5 1 3]
 [7 2 6]
 [8 4 9]]


In [41]:
# sort the data along axis = 1 meaning row wise
sorted_arr_axis1 = np.sort(arr2, axis=1)
print(sorted_arr_axis1)

[[2 3 5]
 [1 6 8]
 [4 7 9]]


In [42]:
sorted_arr_default_axis = np.sort(arr2)
print(sorted_arr_default_axis)

[[2 3 5]
 [1 6 8]
 [4 7 9]]


Concatenation

In [43]:
a

array([1, 2, 3])

In [44]:
b

array([4, 5, 6])

In [45]:
result = np.concatenate((a, b))
print(result)

[1 2 3 4 5 6]


Reshaping

In [46]:
arr_1d

array([1, 2, 3, 4, 5, 6, 7, 8])

In [47]:
arr2d = arr_1d.reshape(4, 2)

In [48]:
print(arr2d)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [49]:
arr2d = arr_1d.reshape(2, 4)

In [50]:
print(arr2d)

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
arr3d = arr_1d.reshape(2, 2, 2)

In [52]:
print(arr3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


Flatten -> converting higher dimesional data into 1D

In [54]:
arr1d = arr3d.reshape(-1)
print(arr1d)

[1 2 3 4 5 6 7 8]


Splitting the arrays

In [57]:
split_arr = np.split(arr1d, 2)
print(split_arr)

[array([1, 2, 3, 4]), array([5, 6, 7, 8])]


Statistical Operations

In [58]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

mean_all = np.mean(arr)

In [59]:
print(mean_all)

3.5


In [60]:
mean_column_wise = np.mean(arr, axis=0)
print(mean_column_wise)

[2.5 3.5 4.5]


In [61]:
mean_row_wise = np.mean(arr, axis=1)
print(mean_row_wise)

[2. 5.]


In [62]:
median_all = np.median(arr)
print(median_all)

3.5


In [63]:
standard_deviation_all = np.std(arr)
print(standard_deviation_all)

1.707825127659933


In [64]:
min_all = np.min(arr)
print(min_all)

1


In [65]:
max_all = np.max(arr)
print(max_all)

6


In [66]:
sum_all = np.sum(arr)
print(sum_all)

21


Creation of arrays using NumPy

In [67]:
a = np.zeros(5)
print(a)

[0. 0. 0. 0. 0.]


In [68]:
b = np.zeros((5, 2))
print(b)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [69]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [70]:
a = np.full(5, 7)
print(a)

[7 7 7 7 7]


In [71]:
a = np.full((3, 4), 3.14)
print(a)

[[3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14]]


In [72]:
a = np.full((2, 3, 4), 3.14)
print(a)

[[[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]

 [[3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]
  [3.14 3.14 3.14 3.14]]]


In [73]:
identity_3_3 = np.eye(3)
print(identity_3_3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.arange(start, end, step_size)

end -> exclusive

In [75]:
np.arange(3, 13, 2)

array([ 3,  5,  7,  9, 11])

In [76]:
np.arange(10, 100, 5)

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [85]:
arr_1d = np.random.random(5)
print(arr_1d)

[0.32397881 0.56065671 0.15360355 0.07635192 0.15620869]


In [84]:
arr_2d = np.random.random((2,3))
print(arr_2d)

[[0.4723162  0.81264635 0.00114594]
 [0.34577782 0.3434144  0.56561573]]


In [81]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [82]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])