In [39]:
#import tensorflow library.
import tensorflow as tf
import numpy as np

01. Basic

In [25]:
#check vertion
print(tf.__version__)

#Scaler =>0D
a = tf.constant(10)
print(a)

#Vector => 1D tensor
print(tf.constant([1,2,3]))

#Matrix = 2D tensor
matrix =  tf.constant([[1,2,3],[4,5,6],[7,8,9]])
print(matrix)

#shape
print(matrix.shape)

#Data Type
print(matrix.dtype)

#Note : Constant Can't change value but into variable we can do it.
#Variable
weight = tf.Variable(10)
print(weight)

#Value Change
weight.assign(20)
print(weight)




2.21.0
tf.Tensor(10, shape=(), dtype=int32)
tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)
(3, 3)
<dtype: 'int32'>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=10>
<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=20>


2. Basic Operations

In [28]:
#add
a = tf.constant(50)
b = tf.constant(60)

print(f'Addition of two{a},{b} numbers is {a+b}')

print(f'Subtraction of two{a},{b} numbers is {a-b}')

print(f'multiply of two{a},{b} numbers is {a*b}')

print(f'deverion of two{a},{b} numbers is {a/b}')


Addition of two50,60 numbers is 110
Subtraction of two50,60 numbers is -10
multiply of two50,60 numbers is 3000
deverion of two50,60 numbers is 0.8333333333333334


3. TensorFlow Math

In [31]:
#reduce_sum
a = tf.constant([1,2,3])
print(tf.reduce_sum(a))

#Mean
print(tf.reduce_mean(a))


tf.Tensor(6, shape=(), dtype=int32)
tf.Tensor(2, shape=(), dtype=int32)


4.Random Tensor

In [32]:
random = tf.random.normal(shape=(2,3))

print(random)

tf.Tensor(
[[-1.2188731   1.1799093  -0.23940614]
 [-0.1685799   1.1483839   0.7984183 ]], shape=(2, 3), dtype=float32)


5.zeros

In [34]:
zero = tf.zeros((2,3))
print(zero)

tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)


6.ones

In [38]:
one = tf.ones((2,3))
print(one)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


7.Convert NumPy to Tensor

In [40]:
arr = np.array([10,20,30])

tensor = tf.convert_to_tensor(arr)

print(tensor)

tf.Tensor([10 20 30], shape=(3,), dtype=int64)


7. Convert Tensor to NumPy

In [42]:
tensor = tf.constant([1,2,3])
print(tensor.numpy())

[1 2 3]


8. Build Your First Neural Network

   ***Suppose hamare paas student ke exam marks hain aur hame pass/fail predict karna hai.***

In [50]:
#Import library
from tensorflow.keras.models import Sequential 
from tensorflow.keras.layers import Dense 

#Build Neural Network
model = Sequential([
    Dense(8, activation="relu"),
    Dense(1, activation="sigmoid")  #output layer for probability score between 0 and 1
])

#Compile Model
model.compile(
    optimizer="adam",
    loss="binary_crossentropy", #sparse_categorical_crossentropy use onlyfor two classlike cate,Dog and sparse_categorical_crossentropy morethen two classes like 0,1,3
    metrics=["accuracy"]
)

'''
Optimizer: Weights kaise update honge.
Loss: Kitni galti hui.
Accuracy: Kitna sahi predict kiya.
'''

#Train Model
model.fit(
    X_train,
    y_train,
    epochs=10,
    batch_size=32
)

'''
X_train → Input data
y_train → Correct answers (labels)
epochs=10 → Poora dataset 10 baar dekhega.
batch_size=32 → Ek baar me 32 samples se weights update karega.
'''


# Evaluate
model.evaluate(X_test, y_test)
'''Ye test data par model ki performance batata hai.'''

# Prediction
prediction = model.predict(X_test)

print(prediction)

# Output (example)

NameError: name 'X_train' is not defined