Local system: pip install pandas

In [3]:
import pandas as pd
import numpy as np
import seaborn as sns
from sklearn.datasets import load_breast_cancer

In [4]:
data = sns.load_dataset("tips")
data.head()

,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [5]:
type(data)

pandas.core.frame.DataFrame

In [6]:
type(data['sex'])

pandas.core.series.Series

In [8]:
type(data[['sex', 'day']])

pandas.core.frame.DataFrame

Customized Series

In [9]:
data = [10, 20, 30, 40, 50, 60]
series1 = pd.Series(data)
series1

,0
0,10
1,20
2,30
3,40
4,50
5,60


In [10]:
data = [10, 20, 30, 40, 50, 60]
series2 = pd.Series(data, index=['a', 'b', 'c', 'd', 'e', 'f'])
series2

,0
a,10
b,20
c,30
d,40
e,50
f,60


In [11]:
s1 = pd.Series([10, 20, 30], index = ['a', 'b', 'c'])
s2 = pd.Series([5, 15, 25], index = ['b', 'c', 'd'])

result = s1 + s2

print(result)

a     NaN
b    25.0
c    45.0
d     NaN
dtype: float64


In [12]:
a1 = np.array([10, 20, 30])
a2 = np.array([5, 15, 25])

print(a1 + a2)

[15 35 55]


Create a series from a NumPy array

In [13]:
a1

array([10, 20, 30])

In [14]:
a1_series = pd.Series(a1, index = ['a', 'b', 'c'])
a1_series

,0
a,10
b,20
c,30


In [28]:
print(a1_series.iloc[1])

20


In [30]:
print(a1_series.loc['b'])

20


Create a series from a dictionary

In [15]:
data = {'Alice':30, 'Bob':35, 'Charlie':28}

series = pd.Series(data)
print(series)

Alice      30
Bob        35
Charlie    28
dtype: int64


In [18]:
dataframe = pd.DataFrame([data])
dataframe

,Alice,Bob,Charlie
0,30,35,28


In [19]:
data

{'Alice': 30, 'Bob': 35, 'Charlie': 28}

In [20]:
data = pd.read_excel('/content/customers.xlsx')

# head() method used to access the top 5 records in a given dataframe
data.head()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0


Access the columns: [email, gender, street_name, city, state]

Access the rows: [1, 2, 5, 9, 12]

In [31]:
data.loc[(1,2,5,9,12),["email","gender","street_name","city","state"]]

,email,gender,street_name,city,state
1,cmolyneaux1@wiley.com,Male,NaN,El Paso,Texas
2,bwestrip2@symantec.com,Female,Arkansas,San Antonio,Texas
5,mcullip5@tiny.cc,Female,Packers,Baltimore,Maryland
9,spoulden9@xing.com,Female,Pond,New Orleans,Louisiana
12,mmacwhanc@patch.com,Male,Eagle Crest,Bronx,New York


iloc vs loc -> to access the values in a given dataframe

In [34]:
data.iloc[[1,2,5,9,12],[3,4,6,8,9]]

,email,gender,street_name,city,state
1,cmolyneaux1@wiley.com,Male,NaN,El Paso,Texas
2,bwestrip2@symantec.com,Female,Arkansas,San Antonio,Texas
5,mcullip5@tiny.cc,Female,Packers,Baltimore,Maryland
9,spoulden9@xing.com,Female,Pond,New Orleans,Louisiana
12,mmacwhanc@patch.com,Male,Eagle Crest,Bronx,New York


iloc -> you can access any row/column using the index numbers only

In [21]:
first_name_column = data.iloc[:, 1]

In [22]:
first_name_column

,first_name
0,Romain
1,Cosimo
2,Bambi
3,Roarke
4,Mikaela
...,...
995,Merrili
996,Winonah
997,Tobit
998,Issiah


Access the column as 'street_name'

In [23]:
street_name_column = data.iloc[:, 6]

In [24]:
street_name_column

,street_name
0,Trailsway
1,NaN
2,Arkansas
3,Debs
4,2nd
...,...
995,Thompson
996,Rowland
997,Basil
998,Kenwood


Access the rows having index number [1, 2, 3] and the column name [firstName, lastName, Gender]

In [25]:
data.iloc[1:4, [1, 2, 4]]

,first_name,last_name,gender
1,Cosimo,Molyneaux,Male
2,Bambi,Westrip,Female
3,Roarke,Pankettman,Male


loc -> to access the elements using the label-based indexing

In [26]:
data.loc[1:4, ['first_name', 'last_name', 'gender']]

,first_name,last_name,gender
1,Cosimo,Molyneaux,Male
2,Bambi,Westrip,Female
3,Roarke,Pankettman,Male
4,Mikaela,Althorpe,NaN


Attributes

In [36]:
# index -> return an index object contains the row lables of the dataframe
data.index

RangeIndex(start=0, stop=1000, step=1)

In [37]:
# shape -> return the (number of rows, number of columns) in a given dataframe
data.shape

(1000, 11)

In [38]:
data.columns

Index(['id', 'first_name', 'last_name', 'email', 'gender', 'street_num',
       'street_name', 'street_suffix', 'city', 'state', 'postcode'],
      dtype='object')

In [39]:
data.dtypes

,0
id,int64
first_name,object
last_name,object
email,object
gender,object
street_num,float64
street_name,object
street_suffix,object
city,object
state,object


In [40]:
data.values

array([[1, 'Romain', 'Southcott', ..., 'San Diego', 'California',
        92127.0],
       [2, 'Cosimo', 'Molyneaux', ..., 'El Paso', 'Texas', nan],
       [3, 'Bambi', 'Westrip', ..., 'San Antonio', 'Texas', 78220.0],
       ...,
       [998, 'Tobit', 'Birt', ..., 'Waterbury', 'Connecticut', 6721.0],
       [999, 'Issiah', 'Standbrooke', ..., 'Savannah', 'Georgia',
        31405.0],
       [1000, 'Elmore', 'Malpas', ..., 'Atlanta', 'Georgia', 30386.0]],
      dtype=object)

In [41]:
data.size

11000

In [42]:
data.empty

False

In [43]:
data.ndim

2

Functions in a dataframe

In [44]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   id             1000 non-null   int64  
 1   first_name     1000 non-null   object 
 2   last_name      1000 non-null   object 
 3   email          878 non-null    object 
 4   gender         957 non-null    object 
 5   street_num     738 non-null    float64
 6   street_name    963 non-null    object 
 7   street_suffix  963 non-null    object 
 8   city           921 non-null    object 
 9   state          920 non-null    object 
 10  postcode       843 non-null    float64
dtypes: float64(2), int64(1), object(8)
memory usage: 86.1+ KB


In [46]:
data.isnull().sum()

,0
id,0
first_name,0
last_name,0
email,122
gender,43
street_num,262
street_name,37
street_suffix,37
city,79
state,80


In [47]:
data.head(20)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
5,6,Magdalena,Cullip,mcullip5@tiny.cc,Female,9190.0,Packers,Drive,Baltimore,Maryland,21229.0
6,7,Marietta,Heball,mheball6@blog.com,Female,12.0,Mallory,Center,Carol Stream,Illinois,60351.0
7,8,Tine,McSperrin,tmcsperrin7@statcounter.com,NaN,530.0,Erie,Plaza,Kansas City,Missouri,64193.0
8,9,Enrichetta,de Villier,edevillier8@ox.ac.uk,Female,745.0,Annamark,Street,Fairbanks,Alaska,99709.0
9,10,Sari,Poulden,spoulden9@xing.com,Female,2.0,Pond,Hill,New Orleans,Louisiana,NaN


In [48]:
data.tail()

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0
999,1000,Elmore,Malpas,NaN,Male,205.0,Farwell,Park,Atlanta,Georgia,30386.0


In [49]:
data.tail(20)

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
980,981,Phylys,Taggerty,ptaggertyr8@epa.gov,Female,92462.0,Maple,Court,Nashville,Tennessee,37250.0
981,982,Judith,Otham,NaN,Female,96973.0,Saint Paul,Avenue,Arlington,Texas,76096.0
982,983,Allison,Coogan,acooganra@auda.org.au,Female,81.0,Thompson,Drive,Orange,California,92867.0
983,984,Adolph,Hammerton,ahammertonrb@quantcast.com,Male,NaN,Basil,Crossing,Orlando,Florida,32813.0
984,985,Tailor,Sealeaf,tsealeafrc@irs.gov,Male,NaN,Summer Ridge,Pass,Beaufort,South Carolina,29905.0
985,986,Lidia,Glendza,lglendzard@techcrunch.com,Female,90.0,Golf Course,Circle,Clearwater,Florida,NaN
986,987,Eric,Mountford,emountfordre@blogspot.com,Male,NaN,6th,Court,Las Vegas,Nevada,89125.0
987,988,Angelica,Ludlamme,aludlammerf@unc.edu,Female,5849.0,Steensland,Park,Saint Petersburg,Florida,NaN
988,989,Vivianne,Abbyss,vabbyssrg@squarespace.com,Female,53592.0,Larry,Road,Santa Cruz,California,95064.0
989,990,Mari,Carberry,mcarberryrh@eventbrite.com,Female,NaN,1st,Drive,Washington,District of Columbia,20546.0


In [50]:
data

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
0,1,Romain,Southcott,rsouthcott0@clickbank.net,Male,1.0,Trailsway,Road,San Diego,California,92127.0
1,2,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,NaN,El Paso,Texas,NaN
2,3,Bambi,Westrip,bwestrip2@symantec.com,Female,4057.0,Arkansas,Circle,San Antonio,Texas,78220.0
3,4,Roarke,Pankettman,rpankettman3@wiley.com,Male,74.0,Debs,Point,Memphis,Tennessee,38150.0
4,5,Mikaela,Althorpe,malthorpe4@51.la,NaN,NaN,2nd,Drive,NaN,NaN,83732.0
...,...,...,...,...,...,...,...,...,...,...,...
995,996,Merrili,Alman,malmanrn@cornell.edu,Female,0.0,Thompson,Way,Reading,Pennsylvania,19610.0
996,997,Winonah,Heckle,whecklero@fc2.com,Female,701.0,Rowland,Hill,Indianapolis,Indiana,46278.0
997,998,Tobit,Birt,NaN,Male,2.0,Basil,Road,Waterbury,Connecticut,6721.0
998,999,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,NaN,Kenwood,Drive,Savannah,Georgia,31405.0


Summary of the descriptive statistics

In [54]:
data.describe()

,id,street_num,postcode
count,1000.000000,738.000000,843.000000
mean,500.500000,10536.439024,52669.548043
std,288.819436,23050.537603,28140.041026
min,1.000000,0.000000,214.000000
25%,250.750000,21.000000,29279.500000
50%,500.500000,445.500000,48232.000000
75%,750.250000,6918.500000,78337.500000
max,1000.000000,99918.000000,99812.000000


In [55]:
data.describe(include='all')

,id,first_name,last_name,email,gender,street_num,street_name,street_suffix,city,state,postcode
count,1000.000000,1000,1000,878,957,738.000000,963,963,921,920,843.000000
unique,NaN,932,993,878,2,NaN,427,21,296,48,NaN
top,NaN,Berty,Sedworth,istandbrookerq@yellowpages.com,Male,NaN,Weeping Birch,Place,Washington,Texas,NaN
freq,NaN,4,3,1,485,NaN,6,57,29,107,NaN
mean,500.500000,NaN,NaN,NaN,NaN,10536.439024,NaN,NaN,NaN,NaN,52669.548043
std,288.819436,NaN,NaN,NaN,NaN,23050.537603,NaN,NaN,NaN,NaN,28140.041026
min,1.000000,NaN,NaN,NaN,NaN,0.000000,NaN,NaN,NaN,NaN,214.000000
25%,250.750000,NaN,NaN,NaN,NaN,21.000000,NaN,NaN,NaN,NaN,29279.500000
50%,500.500000,NaN,NaN,NaN,NaN,445.500000,NaN,NaN,NaN,NaN,48232.000000
75%,750.250000,NaN,NaN,NaN,NaN,6918.500000,NaN,NaN,NaN,NaN,78337.500000


In [52]:
data.transpose()

,0,1,2,3,4,5,6,7,8,9,...,990,991,992,993,994,995,996,997,998,999
id,1,2,3,4,5,6,7,8,9,10,...,991,992,993,994,995,996,997,998,999,1000
first_name,Romain,Cosimo,Bambi,Roarke,Mikaela,Magdalena,Marietta,Tine,Enrichetta,Sari,...,Susana,Silvie,Johnath,Binnie,Brana,Merrili,Winonah,Tobit,Issiah,Elmore
last_name,Southcott,Molyneaux,Westrip,Pankettman,Althorpe,Cullip,Heball,McSperrin,de Villier,Poulden,...,Pere,Silverlock,Clancy,Dearth,Dixon,Alman,Heckle,Birt,Standbrooke,Malpas
email,rsouthcott0@clickbank.net,cmolyneaux1@wiley.com,bwestrip2@symantec.com,rpankettman3@wiley.com,malthorpe4@51.la,mcullip5@tiny.cc,mheball6@blog.com,tmcsperrin7@statcounter.com,edevillier8@ox.ac.uk,spoulden9@xing.com,...,spereri@scribd.com,ssilverlockrj,jclancyrk@smugmug.com,bdearthrl@ed.gov,bdixonrm@myspace.com,malmanrn@cornell.edu,whecklero@fc2.com,NaN,istandbrookerq@yellowpages.com,NaN
gender,Male,Male,Female,Male,NaN,Female,Female,NaN,Female,Female,...,Female,Female,Female,NaN,Female,Female,Female,Male,Male,Male
street_num,1.0,NaN,4057.0,74.0,NaN,9190.0,12.0,530.0,745.0,2.0,...,5018.0,NaN,7.0,8993.0,97.0,0.0,701.0,2.0,NaN,205.0
street_name,Trailsway,NaN,Arkansas,Debs,2nd,Packers,Mallory,Erie,Annamark,Pond,...,Clemons,Elka,Washington,Elgar,Truax,Thompson,Rowland,Basil,Kenwood,Farwell
street_suffix,Road,NaN,Circle,Point,Drive,Drive,Center,Plaza,Street,Hill,...,Way,Avenue,Crossing,Trail,Avenue,Way,Hill,Road,Drive,Park
city,San Diego,El Paso,San Antonio,Memphis,NaN,Baltimore,Carol Stream,Kansas City,Fairbanks,New Orleans,...,Baton Rouge,Utica,Juneau,Minneapolis,Maple Plain,Reading,Indianapolis,Waterbury,Savannah,Atlanta
state,California,Texas,Texas,Tennessee,NaN,Maryland,Illinois,Missouri,Alaska,Louisiana,...,NaN,New York,Alaska,Minnesota,Minnesota,Pennsylvania,Indiana,Connecticut,Georgia,Georgia


In [56]:
df_cat = data.select_dtypes(include='object')
df_cat

,first_name,last_name,email,gender,street_name,street_suffix,city,state
0,Romain,Southcott,rsouthcott0@clickbank.net,Male,Trailsway,Road,San Diego,California
1,Cosimo,Molyneaux,cmolyneaux1@wiley.com,Male,NaN,NaN,El Paso,Texas
2,Bambi,Westrip,bwestrip2@symantec.com,Female,Arkansas,Circle,San Antonio,Texas
3,Roarke,Pankettman,rpankettman3@wiley.com,Male,Debs,Point,Memphis,Tennessee
4,Mikaela,Althorpe,malthorpe4@51.la,NaN,2nd,Drive,NaN,NaN
...,...,...,...,...,...,...,...,...
995,Merrili,Alman,malmanrn@cornell.edu,Female,Thompson,Way,Reading,Pennsylvania
996,Winonah,Heckle,whecklero@fc2.com,Female,Rowland,Hill,Indianapolis,Indiana
997,Tobit,Birt,NaN,Male,Basil,Road,Waterbury,Connecticut
998,Issiah,Standbrooke,istandbrookerq@yellowpages.com,Male,Kenwood,Drive,Savannah,Georgia


In [57]:
df_num = data.select_dtypes(include=['int64', 'float64'])
df_num

,id,street_num,postcode
0,1,1.0,92127.0
1,2,NaN,NaN
2,3,4057.0,78220.0
3,4,74.0,38150.0
4,5,NaN,83732.0
...,...,...,...
995,996,0.0,19610.0
996,997,701.0,46278.0
997,998,2.0,6721.0
998,999,NaN,31405.0


In [59]:
df_num = data.select_dtypes(include='number')
df_num

,id,street_num,postcode
0,1,1.0,92127.0
1,2,NaN,NaN
2,3,4057.0,78220.0
3,4,74.0,38150.0
4,5,NaN,83732.0
...,...,...,...
995,996,0.0,19610.0
996,997,701.0,46278.0
997,998,2.0,6721.0
998,999,NaN,31405.0


Operations on rows and columns in a dataframe