Creation of 1D, 2D and 3D array and it's attributes

pip install numpy -> in your local environment, it's important to install the module first and then start working on it to avoid any errors.

In [1]:
import numpy as np

1D Array

In [2]:
arr_1d = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print(arr_1d)

[1 2 3 4 5 6 7 8]


1 Dimensional array

In [3]:
type(arr_1d)

numpy.ndarray

In [7]:
arr_1d.ndim

1

Shape Of the array

In [10]:
arr_1d.shape

(8,)

Size: indicates the total count of the array elements

In [17]:
arr_1d.size

8

dtype: indicates the data type of the elements within the array

In [21]:
arr_1d.dtype

dtype('int64')

itemsize: size in bytes of each element in the array

In [22]:
arr_1d.itemsize

8

2D Array

In [4]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print(arr_2d)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


2 Dimensional array

In [8]:
arr_2d.ndim

2

In [11]:
arr_2d.shape

(3, 3)

In [19]:
arr_2d.size

9

In [23]:
arr_2d.itemsize

8

3D Array

In [13]:
arr_3d = np.array([[[1, 2],
                    [3, 4]],

                   [[5, 6],
                   [7, 8]],

                   [[9, 10],
                    [11, 12]]])

3 Dimensional array

In [14]:
print(arr_3d)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [15]:
arr_3d.ndim

3

In [16]:
arr_3d.shape

(3, 2, 2)

In [20]:
arr_3d.size

12

Indexing, Mathematical Operations

In [24]:
f = open("/content/data.text", "w")
f.write("Hello")
f.write("World")
f.close()

In [25]:
f = open("/content/data.text", "r")
content = f.read()
print(content)

HelloWorld


In [26]:
with open("/content/data.text", "r") as f:
  content = f.read()
  print(content)

HelloWorld
