Import all the required libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split

Data Preparation

In [2]:
data = {
   'text': [
       # Spam Messages (Keywords: Win, Free, Cash, Urgent)
       "Win a free lottery ticket now",
       "Free money for you",
       "Call now to claim your prize",
       "URGENT: You have won a cash prize",
       "Exclusive offer just for you",
       "Text WIN to 12345 to enter",
       "Congratulations, you won a free gift",
       "Claim your entry into our weekly lottery",

       # Ham Messages (Keywords: Meeting, Lunch, Mom, Home)
       "Hey, are we still meeting for lunch?",
       "Can you pick up milk on your way home?",
       "Mom called earlier, call her back",
       "Let's go to the park tomorrow",
       "Did you finish the report yet?",
       "I missed your call, sorry",
       "Meeting at 2pm is confirmed",
       "Love you, see you later"
   ],
   'label': [
       'spam', 'spam', 'spam', 'spam', 'spam', 'spam', 'spam', 'spam',
       'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham', 'ham'
   ]
}

In [3]:
df = pd.DataFrame(data)
df

,text,label
0,Win a free lottery ticket now,spam
1,Free money for you,spam
2,Call now to claim your prize,spam
3,URGENT: You have won a cash prize,spam
4,Exclusive offer just for you,spam
5,Text WIN to 12345 to enter,spam
6,"Congratulations, you won a free gift",spam
7,Claim your entry into our weekly lottery,spam
8,"Hey, are we still meeting for lunch?",ham
9,Can you pick up milk on your way home?,ham


Vectorization (Text -> Numbers)

In [4]:
vectorizer = CountVectorizer()
X = vectorizer.fit_transform(df['text'])
X

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 90 stored elements and shape (16, 65)>

In [5]:
vectorizer.get_feature_names_out()

array(['12345', '2pm', 'are', 'at', 'back', 'call', 'called', 'can',
       'cash', 'claim', 'confirmed', 'congratulations', 'did', 'earlier',
       'enter', 'entry', 'exclusive', 'finish', 'for', 'free', 'gift',
       'go', 'have', 'her', 'hey', 'home', 'into', 'is', 'just', 'later',
       'let', 'lottery', 'love', 'lunch', 'meeting', 'milk', 'missed',
       'mom', 'money', 'now', 'offer', 'on', 'our', 'park', 'pick',
       'prize', 'report', 'see', 'sorry', 'still', 'text', 'the',
       'ticket', 'to', 'tomorrow', 'up', 'urgent', 'way', 'we', 'weekly',
       'win', 'won', 'yet', 'you', 'your'], dtype=object)

In [6]:
y = df['label']

In [8]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

# split data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
model = MultinomialNB()
model.fit(X_train, y_train)

MultinomialNB()

In [9]:
y_pred = model.predict(X_test)
print(y_pred)

['spam' 'spam' 'spam' 'ham']


In [10]:
accuracy_score(y_test, y_pred)

1.0

In [11]:
new_message = ['Hey, do you want to go for dinner tonight?',
               'CONGRATULATIONS! You won a free iPhone. Click here to view more details.']

new_message_vectorized = vectorizer.transform(new_message)
pred = model.predict(new_message_vectorized)
print(pred)

['ham' 'spam']


Implementation on continuous data

In [13]:
from sklearn.naive_bayes import GaussianNB
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y = True)

In [15]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [17]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [18]:
data = load_iris()
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

Data Split

In [19]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=44)

In [20]:
model = GaussianNB()
model.fit(X_train, y_train)

GaussianNB()

In [21]:
y_pred = model.predict(X_test)
y_pred

array([2, 0, 1, 1, 2, 0, 2, 2, 2, 1, 0, 2, 0, 2, 0, 0, 2, 1, 0, 2, 1, 2,
       2, 1, 2, 1, 0, 1, 0, 1])

In [22]:
accuracy_score(y_test, y_pred)

0.9333333333333333

In [23]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[ 9,  0,  0],
       [ 0,  8,  1],
       [ 0,  1, 11]])